services:
    smtp:
        image: juanluisbaptiste/postfix:1.8.0
        restart: always
        expose:
            - "25"
        volumes:
            - ./mail-spool:/var/spool/postfix
            # you can store mail log in a volume
            # (but create the file locally before startup)
            #- ./logs/smtp/maillog:/var/log/maillog
        environment:
            SMTP_SERVER: ${SMTP_SERVER}
            SMTP_PORT: ${SMTP_PORT}
            SMTP_USERNAME: ${SMTP_USERNAME}
            SMTP_PASSWORD:  ${SMTP_PASSWORD}
            SERVER_HOSTNAME: ${SERVER_HOSTNAME}

    php:
        build:
            context: ./docker/php
        user: 1000:1000
        ports:
            - "127.0.0.1:${HOTCRP_PORT}:9000"
        restart: always
        volumes:
            - ./app:/srv/www/api:ro
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./docker/php/msmtprc:/etc/msmtprc
            - ./docker/php/php.conf:/usr/local/etc/php/conf.d/custom.ini:ro
            - ./logs/php:/var/log
            - ./docs:/docs
        environment:
            MYSQL_USER: ${HOTCRP_DB_NAME:-hotcrp}
            MYSQL_PASSWORD: ${HOTCRP_DB_PASSWORD:-hotcrppwd}
            MYSQL_DATABASE: ${HOTCRP_DB_NAME:-hotcrp}
            MYSQL_HOST: ${HOTCRP_DB_HOST:-mysql}
            HOTCRP_PAPER_SITE: ${HOTCRP_PAPER_SITE}
            HOTCRP_SHORT_NAME: ${HOTCRP_SHORT_NAME}
            HOTCRP_LONG_NAME: ${HOTCRP_LONG_NAME}
            HOTCRP_CONTACT_NAME: ${HOTCRP_CONTACT_NAME}
            HOTCRP_EMAIL_CONTACT: ${HOTCRP_EMAIL_CONTACT}
            HOTCRP_EMAIL_FROM:  ${HOTCRP_EMAIL_FROM}
            HOTCRP_FILESYSTEM_DOCS: ${HOTCRP_FILESYSTEM_DOCS}
        depends_on:
            - smtp

